force-app/main/default/objects/My_Notes__c/My_Notes__c.object-meta.xml
<CustomObject>
    <label>My Notes</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>My Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Notes__c/fields/Keywords__c.field-meta.xml
<CustomField>
    <fullName>Keywords__c</fullName>
    <label>Keywords</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/TestNoteFactory.cls
@isTest
public class TestNoteFactory {
    public static void generateMyNotes(Integer amount) {
        List<My_Notes__c> myNotes = new List<My_Notes__c>();
        for (Integer i=1; i<=amount; i++) {
            myNotes.add(
                new My_Notes__c(
                    Title__c='title' + i,
                    Description__c='desc'+i,
                    Keywords__c='key'+i
                )
            );
        }
        insert myNotes;
    }
}