force-app/main/default/objects/My_Notes__c/My_Notes__c.object-meta.xml
<CustomObject>
    <label>My Notes</label>
    <nameField>
        <displayFormat>N-{000000}</displayFormat>
        <label>My Notes Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>My Notes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/My_Notes__c/fields/Keywords__c.field-meta.xml
<CustomField>
    <fullName>Keywords__c</fullName>
    <label>Keywords</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/MyNotesControllerTest.cls
@isTest
public class MyNotesControllerTest {
    
    @isTest
    private static void saveNewNoteShouldInsertOneNote() {
        My_Notes__c newNote = new My_Notes__c(
            Title__c='title1',
            Description__c='desc1',
            Keywords__c='key1'
        );
        Test.startTest();
        MyNotesController.saveNewNote(newNote);
        Test.stopTest();
        System.assertEquals(1, [SELECT Id FROM My_Notes__c].size());
    }

    @isTest
    private static void saveNewNoteShouldNotBeInserted() {
        My_Notes__c newNote = new My_Notes__c();
        boolean exceptionWasThrown = false;
        Test.startTest();
        try {
            MyNotesController.saveNewNote(newNote);
        } catch (DmlException e) {

        }
        Test.stopTest();
        System.assertEquals(0, [SELECT Id FROM My_Notes__c].size());
    }
}